const addPatternUrl = "https://midnajt.github.io/AddPattern.github.io/";

export const site = {
  name: "Ewelina & Arkadiusz",
  legalName: "Ewelina i Arkadiusz — strona ślubna",
  city: "Spytkowice",
  url: "https://ewelinaiarkadiusz.pl",
  couple: {
    bride: "Ewelina",
    groom: "Arkadiusz",
    initials: "E & A",
  },
  weddingDate: "2026-11-27",
  calendar: {
    startsAt: "2026-11-27T13:30:00",
    endsAt: "2026-11-28T04:00:00",
    timeZone: "Europe/Warsaw",
    filename: "slub-eweliny-i-arkadiusza.ics",
  },
  phone: "504 964 802",
  phoneHref: "tel:+48504964802",
  email: "Ewelina.Scibor@op.pl",
  emailHref: "mailto:Ewelina.Scibor@op.pl",
  contacts: {
    bride: {
      name: "Ewelina",
      phone: "504 964 802",
      phoneHref: "tel:+48504964802",
      email: "Ewelina.Scibor@op.pl",
      emailHref: "mailto:Ewelina.Scibor@op.pl",
    },
    groom: {
      name: "Arkadiusz",
      phone: "502 811 680",
      phoneHref: "tel:+48502811680",
      email: "Arkadiusz.Strzezek@strzezek.com",
      emailHref: "mailto:Arkadiusz.Strzezek@strzezek.com",
    },
  },
  ceremony: {
    namePl: "Kościół pw. Niepokalanego Poczęcia NMP",
    nameEn: "Church of the Immaculate Conception of the BVM",
    time: "14:00",
    street: "Spytkowice 21",
    postal: "34-745",
    city: "Spytkowice",
    full: "Spytkowice 21, 34-745 Spytkowice",
    mapEmbed:
      "https://maps.google.com/maps?q=Spytkowice+21,+34-745+Spytkowice&hl=pl&z=17&output=embed",
    mapLink: "https://maps.app.goo.gl/2DHPKjdKTAreaYsi9",
  },
  reception: {
    namePl: "Przystań Weselna Spytkowice",
    nameEn: "Przystań Weselna Spytkowice",
    time: "16:30",
    street: "Spytkowice 625",
    postal: "34-745",
    city: "Spytkowice",
    full: "Spytkowice 625, 34-745 Spytkowice",
    url: "https://przystanwkabanosie.pl",
    mapEmbed:
      "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2587.1837584628724!2d19.8485729!3d49.575422599999996!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x4715dffd27afbb79%3A0xba39d971e71c3be0!2sPrzysta%C5%84%20Weselna%20Spytkowice!5e0!3m2!1spl!2spl!4v1787766111407!5m2!1spl!2spl",
    mapLink: "https://maps.app.goo.gl/uJu6aCugbX5ZBVrs7",
  },
  lodging: {
    mapLink: "https://maps.app.goo.gl/LRN6tb7x2QshGbnF7",
    distanceKm: 10,
    driveMinutes: 13,
    checkIn: "16:00",
    checkOut: "15:00",
    breakfastFrom: "7:30",
    breakfastTo: "11:00",
    manager: {
      name: "Ewa Pilch",
      phone: "600 309 929",
      phoneHref: "tel:+48600309929",
    },
  },
  transport: {
    vans: 2,
    seats: 9,
    from: "15:00",
  },
  witnesses: [
    {
      id: "maid",
      initials: "AK",
      name: "Anna Kowalska",
      phone: "500 100 210",
      phoneHref: "tel:+48500100210",
      email: "anna@example.pl",
      emailHref: "mailto:anna@example.pl",
    },
    {
      id: "bestMan",
      initials: "TN",
      name: "Tomasz Nowak",
      phone: "500 100 211",
      phoneHref: "tel:+48500100211",
      email: "tomasz@example.pl",
      emailHref: "mailto:tomasz@example.pl",
    },
  ],
  social: {
    facebook: "https://facebook.com",
  },
  addPattern: {
    name: "AddPattern Marcin Krzysztoszek",
    url: "https://addpattern.pl",
  },
  partners: [
    {
      id: "makeup",
      name: "Atelier Urody „Róża”",
      place: "Nowy Sącz",
      url: addPatternUrl,
    },
    {
      id: "florist",
      name: "Kwiaciarnia Nad Popradem",
      place: "Spytkowice",
      url: addPatternUrl,
    },
    {
      id: "hair",
      name: "Salon „Lok i Warkocz”",
      place: "Stary Sącz",
      url: addPatternUrl,
    },
    {
      id: "tailor",
      name: "Pracownia Krawiecka „Atłas”",
      place: "Nowy Sącz",
      url: addPatternUrl,
    },
    {
      id: "band",
      name: "Kapela „Harnasie znad Popradu”",
      place: "Spytkowice",
      url: addPatternUrl,
    },
    {
      id: "photo",
      name: "Fotografia Ślubna „Chwila”",
      place: "Spytkowice",
      url: addPatternUrl,
    },
  ],
} as const;
